services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: servicelog-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Changemelater!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: